name: Test
description: Lints and tests a Go-based project

inputs:
  go-test-args:
    description: 'Arguments to pass to `go test`'
    required: false
    default: -race;-tags=testing netgo

runs:
  using: composite
  steps:
    - name: Lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        skip-cache: true
    - name: Test
      uses: n8maninger/action-golang-test@aa292dc81b16d34406a9551e629e0cdca00d9418 # v2
      with:
        args: ${{ inputs.go-test-args }}