name: Lint & Test Go

on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.22, 1.23 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure Git # required for golangci-lint on Windows
        if: startsWith(matrix.os, 'windows')
        shell: bash
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: SiaFoundation/workflows/.github/actions/go-test@master
  success: # Use in branch rulesets to ensure all matrix jobs completed successfully
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"
      
          
      



