name: Lint & Test Go

on:
  workflow_call:
    inputs:
      go-test-args:
        description: "Arguments to pass to `go test`"
        type: string
        required: false
      try-build:
        description: "Attempt to build the project"
        type: boolean
        required: false
        default: true

jobs:
  test:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.25, 1.26]
        os: [tenki-standard-medium-4c-8g, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure Git # required for golangci-lint on Windows
        if: startsWith(matrix.os, 'windows')
        shell: bash
        run: git config --global core.autocrlf false
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{ matrix.go-version }}
      - uses: SiaFoundation/workflows/.github/actions/go-test@5a0ded089a415998335b93ec0fc3260ebabc6901 # master
        with:
          go-test-args: ${{ inputs.go-test-args }}
      - name: Build
        if: ${{ inputs.try-build }}
        shell: bash
        run: |
          go mod download
          go build -o bin/ ./...

  success: # Use in branch rulesets to ensure all matrix jobs completed successfully
    needs: test
    runs-on: tenki-standard-small-2c-4g
    steps:
      - run: echo "Success!"
